### PR TITLE
Tuning vertical margins in Download builder

### PR DESCRIPTION
**Pull request by smartcorestudio**
It's a matter of taste, but I prefer it this way

### CODE REVIEW

**Comment by flack** [comment]
@smartcorestudio Yes, I think the margins currently look wrong, too. But unfortunately, this PR is against the wrong branch: Everything in `gh-pages` is generated by the build system , the CSS is generated from the files in this folder: 

https://github.com/openpsa/grid.js/tree/master/docs/template/less

You would have to add your changes to one of the files there (or create a new one and reference it in `docs.less`)

**Comment by meh-uk** [comment]
Ah that will mean that #62 won't do anything useful.

**Comment by smartcorestudio** [comment]
@meh-uk  Sorry guys, seems like I did it in the wrong place. Check #64 please

**Comment by flack** [comment]
superseded by #65

**Pull request closed without merging**
